name = "ClimFlowsRegistry"
uuid = "9946f0f5-8370-471c-88e5-cd090a00034a"
repo = "git@github.com:ClimFlows/JuliaRegistry.git"

[packages]
06215ad7-35ad-433d-8be4-57b5a2a542ba = { name = "CFMultigrid", path = "C/CFMultigrid" }
0684c073-ddb9-4fc7-87c8-9d6eef9b287e = { name = "JaxCall", path = "J/JaxCall" }
0dc8c93d-0116-402a-b00b-85ddfe5501a2 = { name = "CFHydrostatics", path = "C/CFHydrostatics" }
27b57071-4f7a-481a-ba32-ffa10dd904ac = { name = "CFShallowWaters", path = "C/CFShallowWaters" }
3699aaca-035b-4155-96ec-eecb526248de = { name = "CFDomains", path = "C/CFDomains" }
435ea534-530f-4103-a4e2-07b06daf33cf = { name = "CFBoxes", path = "C/CFBoxes" }
45b71fc6-fff6-4b4e-ba1f-6968b823c40d = { name = "CFAnelastics", path = "C/CFAnelastics" }
4c829458-57b5-4508-983f-2f0f605f5bfa = { name = "CFBatchSolvers", path = "C/CFBatchSolvers" }
55a4ed1b-ebae-44a5-bd1f-98d158431b8a = { name = "ClimFlowsTestCases", path = "C/ClimFlowsTestCases" }
5d9104bf-354e-4e91-8ca5-37bef64dfa22 = { name = "MemberFunctions", path = "M/MemberFunctions" }
68475963-a72f-47d4-b871-9c5545ecd1c0 = { name = "ClimFluids", path = "C/ClimFluids" }
6a37069a-9a67-4b2d-a34a-f09ab4b23c7c = { name = "MutatingOrNot", path = "M/MutatingOrNot" }
79282218-dfaf-41aa-91df-a06f65ece871 = { name = "CFTimeSchemes", path = "C/CFTimeSchemes" }
7bce7c31-0f61-4fd7-bdaf-6b04abfa2cc7 = { name = "CookBooks", path = "C/CookBooks" }
92085879-9f60-489a-bbcc-711af821df73 = { name = "OnlineLearningTools", path = "O/OnlineLearningTools" }
9c2ca15e-caec-41c0-a22c-2e93fe5a241f = { name = "CFPlanets", path = "C/CFPlanets" }
9e5c175a-5132-4517-85a1-2957ec255f89 = { name = "SHTnsSpheres", path = "S/SHTnsSpheres" }
a33e4613-43be-4f0e-b500-138f013d70af = { name = "CFCompressible", path = "C/CFCompressible" }
aafcb771-6be4-4a54-aeb4-fb9a94868d38 = { name = "CFTransport", path = "C/CFTransport" }
c98386de-3084-4a91-9df5-5a8c5033d229 = { name = "CFDiffusionSchemes", path = "C/CFDiffusionSchemes" }
d9671a99-3ca0-4253-904b-b84b72e7f5e1 = { name = "SimpleRadiativeTransfer", path = "S/SimpleRadiativeTransfer" }
dd0979db-5334-4d13-8d2e-fa88a4f47f12 = { name = "ClimFlowsPlots", path = "C/ClimFlowsPlots" }
f57ce217-a21f-4063-8e40-561e9bf56723 = { name = "ClimFlowsData", path = "C/ClimFlowsData" }
